name: deploy

on:
  push:
    paths:
      - config/**
      - html/**
      - src/**
      - rspack.config.ts
      - tsconfig.json
      - package.json
      - yarn.lock
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Deploy to github pages
        if: ${{ github.ref == 'refs/heads/dev' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          repository-name: typescript-tutorial-exercises/preview
      - name: Deploy to github pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          repository-name: typescript-tutorial-exercises/typescript-tutorial-exercises.github.io
